/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package desktopreader;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.table.TableModel;

/**
 *
 * @author uset
 */
public class Reading extends javax.swing.JFrame {

    public static int sayac=0;
    public static int sayfa=1;
    public int sayfa_sayisi;
    public int id;
    baglanti b = new baglanti();
    public Reading() throws SQLException, IOException {
        initComponents();
        myInit();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    public Reading(int id) throws SQLException, IOException {
        this.id=id;
        initComponents();
        myInit();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }
    
    public void myInit() throws SQLException, MalformedURLException, IOException{
        BufferedImage img;
        ArrayList<Kitap> list = new ArrayList<>();
        
        b.myRs=b.myStat.executeQuery("select * from books");
        Kitap k;
       
        while(b.myRs.next()){
           k = new Kitap(b.myRs.getString("isbn"),
            b.myRs.getString("book_title"),
            b.myRs.getString("book_author"),
            b.myRs.getInt("year_of_publication"),
            b.myRs.getString("publisher"),
            b.myRs.getString("image_url_s"),
            b.myRs.getString("image_url_m"),
            b.myRs.getString("image_url_l"));
           list.add(k);
        }
        
        if(list.size()%30==0){
            sayfa_sayisi=list.size()/30;
        }
        else
            sayfa_sayisi=(list.size()/30)+1;
        
        
        Object[][] satir = new Object[30][4];
        
        for(int i=0;i<30;i++){
            img=ImageIO.read(new URL(list.get(i).getImageL()));
            ImageIcon icon = new ImageIcon(img.getScaledInstance(150, 220, Image.SCALE_SMOOTH));
            satir[i][0]=icon;
            satir[i][1]=list.get(i).getTitle();
            satir[i][2]=list.get(i).getAuthor();
            satir[i][3]=list.get(i).getISBN();
        }
        String[] columnName = {"Kapak","Name","Author","ISBN"};
        TheModel model = new TheModel(satir, columnName);
        Tablo.setModel(model);
        Tablo.setRowHeight(200);
        Tablo.getColumnModel().getColumn(0).setPreferredWidth(100);
        
        sayfa_no.setText(""+sayfa);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablo = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sayfa_no = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(248, 148, 6));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("_");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("X");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Masaüstü Kitap Okuma");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(1, 50, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-go-back-50.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        Tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tablo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabloMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tablo);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tüm Kitaplar");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-rewind-26.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-back-24.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-more-than-24.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-fast-forward-26.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        sayfa_no.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sayfa_no.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addComponent(jLabel8)
                .addGap(117, 117, 117)
                .addComponent(sayfa_no, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117)
                .addComponent(jLabel9)
                .addGap(57, 57, 57)
                .addComponent(jLabel4)
                .addContainerGap(167, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(338, 338, 338)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)))
                    .addComponent(sayfa_no, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void TabloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabloMouseClicked
        int index = Tablo.getSelectedRow();
        TableModel model2 = Tablo.getModel();
        String kitapAdi = model2.getValueAt(index, 3).toString();
        ReadingInfo r;
        try {
            r = new ReadingInfo(kitapAdi,this.id);
        } catch (SQLException ex) {
            Logger.getLogger(Reading.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_TabloMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        try {
            sayfa=1;
            BufferedImage img;
            ArrayList<Kitap> list = new ArrayList<>();

            b.myRs=b.myStat.executeQuery("select * from books");
            Kitap k;

            while(b.myRs.next()){
                k = new Kitap(b.myRs.getString("isbn"),
                    b.myRs.getString("book_title"),
                    b.myRs.getString("book_author"),
                    b.myRs.getInt("year_of_publication"),
                    b.myRs.getString("publisher"),
                    b.myRs.getString("image_url_s"),
                    b.myRs.getString("image_url_m"),
                    b.myRs.getString("image_url_l"));
                list.add(k);
            }

            Object[][] satir = new Object[30][4];

            for(int i=0;i<30;i++){
                img=ImageIO.read(new URL(list.get(i).getImageL()));
                ImageIcon icon = new ImageIcon(img.getScaledInstance(150, 220, Image.SCALE_SMOOTH));
                satir[i][0]=icon;
                satir[i][1]=list.get(i).getTitle();
                satir[i][2]=list.get(i).getAuthor();
                satir[i][3]=list.get(i).getISBN();
            }
            String[] columnName = {"Kapak","Name","Author","ISBN"};
            TheModel model = new TheModel(satir, columnName);
            Tablo.setModel(model);
            Tablo.setRowHeight(200);
            Tablo.getColumnModel().getColumn(0).setPreferredWidth(100);

            sayfa_no.setText(""+sayfa);
        } catch (SQLException | IOException ex) {
            Logger.getLogger(NewAccount2.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        if(sayac!=0){
            sayac=sayac-30;
        }
        sayfa--;
        sayfa_no.setText(""+sayfa);
        if(sayac>=0){
            try {
                BufferedImage img;
                ArrayList<Kitap> list = new ArrayList<>();

                b.myRs=b.myStat.executeQuery("select * from books limit "+sayac+",30");
                Kitap k;

                while(b.myRs.next()){
                    k = new Kitap(b.myRs.getString("isbn"),
                        b.myRs.getString("book_title"),
                        b.myRs.getString("book_author"),
                        b.myRs.getInt("year_of_publication"),
                        b.myRs.getString("publisher"),
                        b.myRs.getString("image_url_s"),
                        b.myRs.getString("image_url_m"),
                        b.myRs.getString("image_url_l"));
                    list.add(k);
                }

                Object[][] satir = new Object[30][4];

                for(int i=0;i<30;i++){
                    img=ImageIO.read(new URL(list.get(i).getImageL()));
                    ImageIcon icon = new ImageIcon(img.getScaledInstance(150, 220, Image.SCALE_SMOOTH));
                    satir[i][0]=icon;
                    satir[i][1]=list.get(i).getTitle();
                    satir[i][2]=list.get(i).getAuthor();
                    satir[i][3]=list.get(i).getISBN();
                }
                String[] columnName = {"Kapak","Name","Author","ISBN"};
                TheModel model = new TheModel(satir, columnName);
                Tablo.setModel(model);
                Tablo.setRowHeight(200);
                Tablo.getColumnModel().getColumn(0).setPreferredWidth(100);
            } catch (SQLException | IOException ex) {
                Logger.getLogger(Reading.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        sayac=sayac+30;
        sayfa++;
        sayfa_no.setText(""+sayfa);
        try {
            BufferedImage img;
            ArrayList<Kitap> list = new ArrayList<>();

            b.myRs=b.myStat.executeQuery("select * from books limit "+sayac+",30");
            Kitap k;

            while(b.myRs.next()){
                k = new Kitap(b.myRs.getString("isbn"),
                    b.myRs.getString("book_title"),
                    b.myRs.getString("book_author"),
                    b.myRs.getInt("year_of_publication"),
                    b.myRs.getString("publisher"),
                    b.myRs.getString("image_url_s"),
                    b.myRs.getString("image_url_m"),
                    b.myRs.getString("image_url_l"));
                list.add(k);
            }

            Object[][] satir = new Object[30][4];

            for(int i=0;i<30;i++){
                img=ImageIO.read(new URL(list.get(i).getImageL()));
                ImageIcon icon = new ImageIcon(img.getScaledInstance(150, 220, Image.SCALE_SMOOTH));
                satir[i][0]=icon;
                satir[i][1]=list.get(i).getTitle();
                satir[i][2]=list.get(i).getAuthor();
                satir[i][3]=list.get(i).getISBN();
            }
            String[] columnName = {"Kapak","Name","Author","ISBN"};
            TheModel model = new TheModel(satir, columnName);
            Tablo.setModel(model);
            Tablo.setRowHeight(200);
            Tablo.getColumnModel().getColumn(0).setPreferredWidth(100);
        } catch (SQLException | IOException ex) {
            Logger.getLogger(Reading.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        
        if(sayfa_sayisi%30==0){
            sayac=sayfa_sayisi*30;
        }
        else
            sayac=(sayfa_sayisi-1)*30;
        
        sayfa=sayfa_sayisi;
        sayfa_no.setText(""+sayfa);
        
        try {
            BufferedImage img;
            ArrayList<Kitap> list = new ArrayList<>();

            b.myRs=b.myStat.executeQuery("select * from books limit "+sayac+",30");
            Kitap k;

            while(b.myRs.next()){
                k = new Kitap(b.myRs.getString("isbn"),
                    b.myRs.getString("book_title"),
                    b.myRs.getString("book_author"),
                    b.myRs.getInt("year_of_publication"),
                    b.myRs.getString("publisher"),
                    b.myRs.getString("image_url_s"),
                    b.myRs.getString("image_url_m"),
                    b.myRs.getString("image_url_l"));
                list.add(k);
            }

            Object[][] satir = new Object[list.size()][4];

            for(int i=0;i<list.size();i++){
                img=ImageIO.read(new URL(list.get(i).getImageL()));
                ImageIcon icon = new ImageIcon(img.getScaledInstance(150, 220, Image.SCALE_SMOOTH));
                satir[i][0]=icon;
                satir[i][1]=list.get(i).getTitle();
                satir[i][2]=list.get(i).getAuthor();
                satir[i][3]=list.get(i).getISBN();
            }
            String[] columnName = {"Kapak","Name","Author","ISBN"};
            TheModel model = new TheModel(satir, columnName);
            Tablo.setModel(model);
            Tablo.setRowHeight(200);
            Tablo.getColumnModel().getColumn(0).setPreferredWidth(100);
        } catch (SQLException | IOException ex) {
            Logger.getLogger(Reading.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reading.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Reading().setVisible(true);
            } catch (SQLException | IOException ex) {
                Logger.getLogger(Reading.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tablo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel sayfa_no;
    // End of variables declaration//GEN-END:variables
}
